baseURL = ""
languageCode = "en-us"
title = "Maoqide"
theme = "nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "maoqide-1"

# Google Analytics UA number
googleAnalytics = "UA-141682683-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Post"
  weight = 20
  identifier = "post"
  url = "/post/"

# [[menu.main]]
# name = "Works"
# weight = 20
# identifier = "works"
# url = "https://github.com/maoqide"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Maoqide"
  bg = "images/square.svg"
  avatar = "images/golang.svg"
  seotitle = "Maoqide"
  subtitle = "~ Keep Learning ~"
  description = "Maoqide is a personal blog site, recording learning about container, kuberntes, golang..."
  paginate = 10

  # Choose your social networks
  email = "maoqidemail@gmail.com"
  github = "maoqide"
#   twitter = "twitter_username"
#   linkedin = "linkedin_username"
#   weibo = "weibo_username"
#   wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  # stackoverflow = "laozhu"
  # codesandbox = "melaozhu"
  # npm = "laozhu"
  # reddit = "melaozhu"

  # Overrid theme styles in this file
  # customStyle = "styles/custom.scss"

  # Changyan Comments (China Only)
  # changyan = false
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "moDctZ0TPe6VxisyOQD_1YWrlEXu3jHdB1go5ptHRn0"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "0498007A4CDA3EAB6CD23570479B29DA"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  baiduTongji = "c3c6dd2eb79bc741d95463b6040ac868"

  # ICP Number (China Only)
  ICP = "浙ICP备19006182号"

